// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv'
import { defineConfig, env } from 'prisma/config'

// 加载 .env 文件
config({ path: '.env' })

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations'
  },
  engine: 'classic',
  datasource: {
    url: env('DATABASE_URL') || 'file:./prisma/dev.db'
  }
})
