-- 用户表
CREATE TABLE IF NOT EXISTS User (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'USER',
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS User_phone_key ON User(phone);

-- 分类表
CREATE TABLE IF NOT EXISTS Category (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    icon TEXT,
    sort INTEGER NOT NULL DEFAULT 0,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL
);

-- 菜品表
CREATE TABLE IF NOT EXISTS Dish (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price REAL NOT NULL,
    image TEXT,
    categoryId TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'AVAILABLE',
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL,
    CONSTRAINT Dish_categoryId_fkey FOREIGN KEY (categoryId) REFERENCES Category (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- 菜品做法表
CREATE TABLE IF NOT EXISTS DishMethod (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    price REAL NOT NULL DEFAULT 0,
    dishId TEXT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL,
    CONSTRAINT DishMethod_dishId_fkey FOREIGN KEY (dishId) REFERENCES Dish (id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 购物车表
CREATE TABLE IF NOT EXISTS CartItem (
    id TEXT NOT NULL PRIMARY KEY,
    userId TEXT NOT NULL,
    dishId TEXT NOT NULL,
    methodId TEXT,
    quantity INTEGER NOT NULL DEFAULT 1,
    remark TEXT,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL,
    CONSTRAINT CartItem_dishId_fkey FOREIGN KEY (dishId) REFERENCES Dish (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CartItem_methodId_fkey FOREIGN KEY (methodId) REFERENCES DishMethod (id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS CartItem_userId_dishId_methodId_key ON CartItem(userId, dishId, methodId);

-- 订单表
CREATE TABLE IF NOT EXISTS "Order" (
    id TEXT NOT NULL PRIMARY KEY,
    userId TEXT NOT NULL,
    tableNo TEXT,
    status TEXT NOT NULL DEFAULT 'PENDING',
    totalAmount REAL NOT NULL,
    remark TEXT,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL,
    CONSTRAINT Order_userId_fkey FOREIGN KEY (userId) REFERENCES User (id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 订单项表
CREATE TABLE IF NOT EXISTS OrderItem (
    id TEXT NOT NULL PRIMARY KEY,
    orderId TEXT NOT NULL,
    dishId TEXT NOT NULL,
    methodId TEXT,
    quantity INTEGER NOT NULL,
    price REAL NOT NULL,
    remark TEXT,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL,
    CONSTRAINT OrderItem_orderId_fkey FOREIGN KEY (orderId) REFERENCES "Order" (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT OrderItem_dishId_fkey FOREIGN KEY (dishId) REFERENCES Dish (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT OrderItem_methodId_fkey FOREIGN KEY (methodId) REFERENCES DishMethod (id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- 二维码表
CREATE TABLE IF NOT EXISTS QRCode (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    tableNo TEXT,
    scans INTEGER NOT NULL DEFAULT 0,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL
);
